language: node_js

node_js:
  - "lts/carbon"

cache:
  directories:
    - "node_modules"

script:
  - npm test
  - '[ "$TRAVIS_PULL_REQUEST" = "false" ] && npm run test || npm run verify'

git:
  depth: 5